const userStudyText =
["a person side steps to the right and then side steps to the left.",
"a person walks around and stops.",
"a person jogs on the spot.",
"the person is strumming the violin .",
"the person is walking around.",
"person goes from standing to kneeling",
"a person stayed on the place",
"a man slowing walking forward",
"a person walks forward in a straight line with arms spread open",
"a person slowly walks backwards.",
"the person is walking upstairs.",
"a person slowly walks sideways from right to left.",
"a person walks forward and climbs up two steps with both hands by their sides.",
"a person slowly walked forward",
"moving hand back and forth near waist.",
"a person walks forward and stops.",
"a person walks forward and stops.",
"the person is walking forward at a medium speed.",
"a person remained sitting down.",
"a person walks forward in an askew line.",
"a person is walking slowly in zigzag",
"a person walks forward, briefly sits down, and then stands and walk back in the opposite direction.",
"a person moves their arms forward then around in opposite circles",
"a person is combing their hair",
"a person takes one step forward towards the left",
"a person is stumbling forward.",
"person walked from one side to the other.",
"this person runs and ducks under something.",
"a figure walks down and left to stare at a wall",
"person is making stepping motion in place",
"person is walking in us and circles.",
"the man is moving his legs",
"a person walks around in a circle.",
"the person is walking around.",
"a man seems to be walking forward on a straight line",
"a person walks forward at moderate pace.",
"a person crosses his arms.",
"the person work for you turn right and walk back",
"a man is waving both arms above his head 6 times.",
"the person walks in a counterclockwise circle",
"person starts out standing then leans to the left and stomps his right foot.",
"a person sits down to avoid pressure on their knees.",
"the man walks forward then turns and returns back",
"the man runs back wards",
"a man walks backwards for a few steps.",
"a person walks forward slowly.",
"someone walks down a sidewalk and slips",
"a figure walks forward then kneels down and raises their chest",
"a person walks in a curved path to the right.",
"a person stumbling to their right side.",
"the person is jumping up and down.",
];